### PR TITLE
Always log servlet errors on server side

### LINKED ISSUE #212: Improve exception handling in servlets
Currently all servlets catch exception and create a `ServletResponse` to transmit the error to the client. However this will
- never log the error on the server side
- does not emit the throwable's class name
- does not emit a proper title

I propose to always log exceptions on server side and (primarily) rely on `ServletResponse.setError(Throwable)` as that will also emit information about the throwable's class (leverages `Throwable.toString()` instead of  `Throwable.getMessage()`) and set the status code 500 automatically.

### PR DESCRIPTION
**Pull request by kwin**
Also use HTMLResponse for all servlets which don't expose any other content than the status.
Change some status codes to be more in line with ReST principles.

This closes #212

**Checklist before requesting a review**

- [x] Contribution guidelines read in [CONTRIBUTING.md](CONTRIBUTING.md)
- [x] I have performed a self-review of my code
- [x] Tests are added where appropriate
- [x] The resolution of the issue is mentioned in the [CHANGELOG.md](CHANGELOG.md)

### CODE REVIEW

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java [hunk 1]
```diff
@@ -93,10 +105,38 @@ protected void service(@NotNull SlingHttpServletRequest request, @NotNull SlingH
...
+            throws ServletException, IOException {
+        HtmlResponse htmlResponse = new HtmlResponse();
+        try {
+            internalDoPost(request, htmlResponse);
+            htmlResponse.send(response, true);
+        } catch (Throwable e) {
+            if (e instanceof IllegalArgumentException) {
+                throw (IllegalArgumentException)e; // rethrow IllegalArgumentException to be handled by the service method
+            }
+            LOG.error("{}: {}", exceptionMessagePrefix, e.getMessage(), e);
```
Comment (kwin) [inline core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java:126]: stacktrace only with category DEBUG or leave it like this?

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/UpdateMessageEntryServlet.java [hunk 2]
```diff
@@ -48,26 +49,18 @@ public class UpdateMessageEntryServlet extends AbstractDictionaryServlet {
...
-            htmlResponse.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, String.format("Unable to update message entry '%s': %s", combiningMessageEntryPath, e.getMessage()));
-            htmlResponse.send(response, true);
+        Resource combiningMessageEntryResource = resourceResolver.getResource(combiningMessageEntryPath);
+        if (combiningMessageEntryResource != null) {
+            // javasecurity:S5145
+            LOG.debug("Updating message entry for path '{}'...", combiningMessageEntryPath);
+            updateCombiningMessageEntry(request, resourceResolver, combiningMessageEntryResource);
+        } else {
+            // javasecurity:S5145
+            htmlResponse.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR, String.format("No dictionaries to update exist for '%s'", combiningMessageEntryPath));
```
Comment (kwin) [inline core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/UpdateMessageEntryServlet.java:63]: 404 maybe?

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java [hunk 3]
```diff
@@ -32,55 +29,48 @@
...
-                    Optional<String> messageOptional;
-                    if (useEmpty || !message.isEmpty()) {
-                        messageOptional = Optional.of(message);
-                    } else {
-                        messageOptional = Optional.empty();
-                    }
-                    languageDictionary.createEntry(resourceResolver, key, messageOptional);
+        Collection<Dictionary> dictionaries = dictionaryService.getDictionaries(resourceResolver, path);
+        if (dictionaries.isEmpty()) {
+            htmlResponse.setStatus(HttpServletResponse.SC_BAD_REQUEST, String.format("No dictionaries found at path '%s'", path));
```
Comment (kwin) [inline core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java:53]: 404?

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java (hunk 1 above)
Comment (royteeuwen) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java:126]: for me it depends, if it's a client-caused error => debug, if it's an internal server error that we should look at => error

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java (hunk 3 above)
Comment (royteeuwen) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java:53]: If we want to expose the API's as real REST API's => 404. 
If they are tightly bound with our granite ui, then it means someone is doing something fishy and shouldn't be in this situation => 400

So for me both are fine :) I don't think anyone would use these API's outside the framework but you never know

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/UpdateMessageEntryServlet.java (hunk 2 above)
Comment (royteeuwen) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/UpdateMessageEntryServlet.java:63]: same as the previous remark, 404 or 400

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java (hunk 1 above)
Comment (kwin) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java:126]: that is not always unambigously to say, how would you classify a permission issue?
I for now would leave it at this level, later on we can relax if we get too reports (which I don't expect) but right now it helps a lot to improve the tool further to iron out the edge cases.

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java (hunk 3 above)
Comment (kwin) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java:53]: I agree that it shouldn't matter for this case, because the UI exposed error looks the same for both 404 and 400 (and every other non-success status code). However this situation does not necessarily mean someone is doing something fishy.
We are in a heavy concurrent system where arbitrarily many users could potentially modify dictionary resources via multiple means:
- installing content packages covering dictionaries
- working with AEM Dictionary Translator
- working with Adobe's Translator
- working with the Translation Project

Those concurrent situations may easily lead to situations where every client behaves correctly, but still one gets a 404/400 because the underlying repository was meanhwhile removed by someone else.

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java (hunk 1 above)
Comment (kwin) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/AbstractDictionaryServlet.java:126]: The 404 cases should be already caught before.

File: core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java (hunk 3 above)
Comment (royteeuwen) [reply core/src/main/java/be/orbinson/aem/dictionarytranslator/servlets/action/CreateMessageEntryServlet.java:53]: True 👍

**Review by royteeuwen — APPROVED** [review]
